param()

$ErrorActionPreference = 'Stop'
$Generator = Join-Path $PSScriptRoot 'generate-release-sbom.ps1'
$Verifier = Join-Path $PSScriptRoot 'verify-release-sbom.ps1'
. (Join-Path $PSScriptRoot 'release-sbom-common.ps1')

function Write-Utf8NoBom {
  param(
    [Parameter(Mandatory = $true)][string]$Path,
    [Parameter(Mandatory = $true)][string]$Content
  )

  $Parent = Split-Path -Parent $Path
  if (-not (Test-Path -LiteralPath $Parent -PathType Container)) {
    New-Item -ItemType Directory -Path $Parent -Force | Out-Null
  }
  [System.IO.File]::WriteAllText($Path, $Content, [System.Text.UTF8Encoding]::new($false))
}

function Get-TestDigest {
  param([Parameter(Mandatory = $true)][string]$Value)
  return Get-StringSha256Hex $Value
}

function Get-TestSriSha512 {
  param([Parameter(Mandatory = $true)][string]$Value)

  $Algorithm = [System.Security.Cryptography.SHA512]::Create()
  try {
    $Digest = $Algorithm.ComputeHash([System.Text.Encoding]::UTF8.GetBytes($Value))
    return 'sha512-' + [Convert]::ToBase64String($Digest)
  } finally {
    $Algorithm.Dispose()
  }
}

function Invoke-ShouldPass {
  param(
    [Parameter(Mandatory = $true)][string]$Label,
    [Parameter(Mandatory = $true)][scriptblock]$Action
  )
  try {
    & $Action | Out-Null
    return [ordered]@{ name = $Label; passed = $true; expected = 'success' }
  } catch {
    throw "Expected success for '$Label': $($_.Exception.Message)"
  }
}

function Invoke-ShouldFail {
  param(
    [Parameter(Mandatory = $true)][string]$Label,
    [Parameter(Mandatory = $true)][scriptblock]$Action
  )
  try {
    & $Action | Out-Null
  } catch {
    return [ordered]@{ name = $Label; passed = $true; expected = 'failure'; message = $_.Exception.Message }
  }
  throw "Expected failure for '$Label', but the command succeeded."
}

$SystemTemp = [System.IO.Path]::GetFullPath([System.IO.Path]::GetTempPath()).TrimEnd('\', '/')
$TestRoot = Join-Path $SystemTemp ('steel-release-sbom-test-' + [Guid]::NewGuid().ToString('N'))
$FixtureRepo = Join-Path $TestRoot 'repo'
$OutputOne = Join-Path $TestRoot 'sbom-one.cdx.json'
$OutputTwo = Join-Path $TestRoot 'sbom-two.cdx.json'
$TamperedSbom = Join-Path $TestRoot 'sbom-tampered.cdx.json'
$TamperedToolsSbom = Join-Path $TestRoot 'sbom-tools-tampered.cdx.json'
$Cases = @()
$OldHttpProxy = $env:HTTP_PROXY
$OldHttpsProxy = $env:HTTPS_PROXY
$OldNoProxy = $env:NO_PROXY

try {
  New-Item -ItemType Directory -Path $FixtureRepo -Force | Out-Null

  $PackageLock = [ordered]@{
    name = 'steel-sbom-fixture'
    version = '1.2.3'
    lockfileVersion = 3
    requires = $true
    packages = [ordered]@{
      '' = [ordered]@{
        name = 'steel-sbom-fixture'
        version = '1.2.3'
        dependencies = [ordered]@{ react = '18.3.1' }
        devDependencies = [ordered]@{ '@scope/dev-tool' = '2.0.0' }
      }
      'node_modules/react' = [ordered]@{
        version = '18.3.1'
        resolved = 'https://registry.npmjs.org/react/-/react-18.3.1.tgz'
        integrity = Get-TestSriSha512 'react-18.3.1'
        license = 'MIT'
      }
      'node_modules/@scope/dev-tool' = [ordered]@{
        version = '2.0.0'
        resolved = 'https://registry.npmjs.org/@scope/dev-tool/-/dev-tool-2.0.0.tgz'
        integrity = Get-TestSriSha512 '@scope/dev-tool-2.0.0'
        dev = $true
        license = 'Apache-2.0'
      }
    }
  }
  Write-Utf8NoBom -Path (Join-Path $FixtureRepo 'app\client\package-lock.json') -Content (($PackageLock | ConvertTo-Json -Depth 20) + "`n")

  $RegistryChecksum = Get-TestDigest 'serde-1.0.0'
  $CargoDefinitions = @(
    [ordered]@{ path = 'app\client\src-tauri\Cargo.lock'; root = 'fixture-tauri' },
    [ordered]@{ path = 'app\service\Cargo.lock'; root = 'fixture-service' },
    [ordered]@{ path = 'app\trigger\Cargo.lock'; root = 'fixture-trigger' }
  )
  foreach ($Definition in $CargoDefinitions) {
    $CargoLock = @"
# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "$($Definition.root)"
version = "1.2.3"

[[package]]
name = "serde"
version = "1.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "$RegistryChecksum"
"@
    Write-Utf8NoBom -Path (Join-Path $FixtureRepo $Definition.path) -Content ($CargoLock.TrimStart() + "`n")
  }

  $ExternalRows = @(
    [ordered]@{ id = 'msvc'; category = 'cpp-toolchain'; type = 'application'; name = 'MSVC Build Tools'; version = '14.40.33807'; supplier = 'Microsoft Corporation'; scope = 'build'; artifact = 'vs_buildtools.exe'; purl = 'pkg:generic/msvc-build-tools@14.40.33807'; licenses = @('LicenseRef-Microsoft-Visual-Studio') },
    [ordered]@{ id = 'camera-sdk'; category = 'camera-sdk'; type = 'library'; name = 'Fixture Camera SDK'; version = '5.4.3'; supplier = 'Fixture Camera Vendor'; scope = 'runtime'; artifact = 'nvt_lvm_sdk.dll'; purl = 'pkg:generic/fixture-camera-sdk@5.4.3'; licenses = @('LicenseRef-Fixture-Proprietary') },
    [ordered]@{ id = 'vc-redist'; category = 'vc-runtime'; type = 'application'; name = 'VC++ Redistributable x64'; version = '14.40.33810'; supplier = 'Microsoft Corporation'; scope = 'runtime'; artifact = 'VC_redist.x64.exe'; purl = 'pkg:generic/vc-redist-x64@14.40.33810'; licenses = @('LicenseRef-Microsoft-Visual-Cpp-Runtime') },
    [ordered]@{ id = 'webview2'; category = 'webview2-runtime'; type = 'framework'; name = 'WebView2 Runtime x64'; version = '126.0.0.0'; supplier = 'Microsoft Corporation'; scope = 'runtime'; artifact = 'MicrosoftEdgeWebView2RuntimeInstallerX64.exe'; purl = 'pkg:generic/webview2-runtime-x64@126.0.0.0'; licenses = @('LicenseRef-Microsoft-WebView2-Runtime') },
    [ordered]@{ id = 'wix'; category = 'wix-toolset'; type = 'application'; name = 'WiX Toolset'; version = '3.14.1'; supplier = 'WiX Toolset Foundation'; scope = 'build'; artifact = 'wix314-binaries.zip'; purl = 'pkg:generic/wix-toolset@3.14.1'; licenses = @('MS-RL') },
    [ordered]@{ id = 'nsis'; category = 'nsis'; type = 'application'; name = 'NSIS'; version = '3.10'; supplier = 'NSIS Contributors'; scope = 'build'; artifact = 'nsis-3.10.zip'; purl = 'pkg:generic/nsis@3.10'; licenses = @('Zlib') }
  )
  foreach ($Row in $ExternalRows) { $Row['sha256'] = Get-TestDigest ([string]$Row.artifact) }
  $ExternalConfig = [ordered]@{
    schema = 'steel.release-external-components.v1'
    approved = $true
    components = $ExternalRows
  }
  $ExternalPath = Join-Path $FixtureRepo 'config\release\external-components.json'
  Write-Utf8NoBom -Path $ExternalPath -Content (($ExternalConfig | ConvertTo-Json -Depth 20) + "`n")

  & git -C $FixtureRepo init --quiet
  if ($LASTEXITCODE -ne 0) { throw 'git init failed for SBOM fixture.' }
  & git -C $FixtureRepo config user.email 'sbom-test@example.invalid'
  & git -C $FixtureRepo config user.name 'SBOM Test'
  & git -C $FixtureRepo add --all
  & git -C $FixtureRepo commit --quiet -m 'SBOM fixture'
  if ($LASTEXITCODE -ne 0) { throw 'git commit failed for SBOM fixture.' }
  $Commit = ((& git -C $FixtureRepo rev-parse HEAD) | Out-String).Trim().ToLowerInvariant()
  $ExternalHash = Get-Sha256Hex $ExternalPath

  $env:HTTP_PROXY = 'http://127.0.0.1:1'
  $env:HTTPS_PROXY = 'http://127.0.0.1:1'
  $env:NO_PROXY = ''

  $GenerateArgs = @{
    RepoRoot = $FixtureRepo
    ExternalComponentsPath = $ExternalPath
    ExpectedExternalComponentsSha256 = $ExternalHash
    ExpectedCommit = $Commit
    OutputPath = $OutputOne
  }
  $Cases += ,(Invoke-ShouldPass 'offline generation with all six external categories' { & $Generator @GenerateArgs })
  $VerifyArgs = @{
    SbomPath = $OutputOne
    RepoRoot = $FixtureRepo
    ExternalComponentsPath = $ExternalPath
    ExpectedExternalComponentsSha256 = $ExternalHash
    ExpectedCommit = $Commit
  }
  $Cases += ,(Invoke-ShouldPass 'offline semantic verification' { & $Verifier @VerifyArgs })

  $GenerateArgs.OutputPath = $OutputTwo
  $Cases += ,(Invoke-ShouldPass 'second deterministic generation' { & $Generator @GenerateArgs })
  if ((Get-Sha256Hex $OutputOne) -cne (Get-Sha256Hex $OutputTwo)) {
    throw 'Repeated generation from the same commit and evidence was not byte-for-byte deterministic.'
  }
  $Cases += ,[ordered]@{ name = 'deterministic output hash'; passed = $true; expected = 'identical' }

  Copy-Item -LiteralPath $OutputOne -Destination $TamperedSbom
  $Tampered = Read-JsonDictionary $TamperedSbom
  $Tampered['components'][0]['version'] = '99.99.99'
  Write-Utf8NoBom -Path $TamperedSbom -Content (($Tampered | ConvertTo-Json -Depth 100) + "`n")
  $TamperedArgs = $VerifyArgs.Clone()
  $TamperedArgs.SbomPath = $TamperedSbom
  $Cases += ,(Invoke-ShouldFail 'tampered SBOM component rejected' { & $Verifier @TamperedArgs })

  Copy-Item -LiteralPath $OutputOne -Destination $TamperedToolsSbom
  $TamperedTools = Read-JsonDictionary $TamperedToolsSbom
  $TamperedTools['metadata']['tools']['components'][1]['version'] = '999.0.0'
  Write-Utf8NoBom -Path $TamperedToolsSbom -Content (($TamperedTools | ConvertTo-Json -Depth 100) + "`n")
  $TamperedToolsArgs = $VerifyArgs.Clone()
  $TamperedToolsArgs.SbomPath = $TamperedToolsSbom
  $Cases += ,(Invoke-ShouldFail 'tampered generator environment rejected' { & $Verifier @TamperedToolsArgs })

  Add-Content -LiteralPath (Join-Path $FixtureRepo 'app\service\Cargo.lock') -Value '# lock tamper' -Encoding ascii
  $DirtyVerifyArgs = $VerifyArgs.Clone()
  $DirtyVerifyArgs.AllowDirtyWorktree = $true
  $Cases += ,(Invoke-ShouldFail 'changed lock hash rejected' { & $Verifier @DirtyVerifyArgs })
  $DirtyGenerateArgs = $GenerateArgs.Clone()
  $DirtyGenerateArgs.OutputPath = Join-Path $TestRoot 'dirty.cdx.json'
  $Cases += ,(Invoke-ShouldFail 'dirty source rejected by default' { & $Generator @DirtyGenerateArgs })
  & git -C $FixtureRepo checkout --quiet -- app/service/Cargo.lock
  if ($LASTEXITCODE -ne 0) { throw 'Failed to restore the SBOM fixture Cargo.lock.' }

  $ProtectedOutputArgs = $GenerateArgs.Clone()
  $ProtectedOutputArgs.OutputPath = Join-Path $FixtureRepo 'app\client\package-lock.json'
  $Cases += ,(Invoke-ShouldFail 'SBOM input overwrite rejected' { & $Generator @ProtectedOutputArgs })

  $MissingCategoryConfig = [ordered]@{
    schema = 'steel.release-external-components.v1'
    approved = $true
    components = @($ExternalRows | Where-Object { $_.category -ne 'nsis' })
  }
  $MissingCategoryPath = Join-Path $TestRoot 'missing-category.json'
  Write-Utf8NoBom -Path $MissingCategoryPath -Content (($MissingCategoryConfig | ConvertTo-Json -Depth 20) + "`n")
  $MissingArgs = $GenerateArgs.Clone()
  $MissingArgs.ExternalComponentsPath = $MissingCategoryPath
  $MissingArgs.ExpectedExternalComponentsSha256 = Get-Sha256Hex $MissingCategoryPath
  $MissingArgs.OutputPath = Join-Path $TestRoot 'missing-category.cdx.json'
  $Cases += ,(Invoke-ShouldFail 'missing external category rejected' { & $Generator @MissingArgs })

  $WrongHashArgs = $GenerateArgs.Clone()
  $WrongHashArgs.OutputPath = Join-Path $TestRoot 'wrong-policy-hash.cdx.json'
  $WrongHashArgs.ExpectedExternalComponentsSha256 = ('a' * 64)
  $Cases += ,(Invoke-ShouldFail 'out-of-band external policy hash mismatch rejected' { & $Generator @WrongHashArgs })

  [ordered]@{
    schema = 'steel.release-sbom-test.v1'
    code = 0
    passed = @($Cases | Where-Object { $_.passed }).Count
    total = $Cases.Count
    offline = $true
    cases = $Cases
  } | ConvertTo-Json -Depth 8
} finally {
  $env:HTTP_PROXY = $OldHttpProxy
  $env:HTTPS_PROXY = $OldHttpsProxy
  $env:NO_PROXY = $OldNoProxy
  $ResolvedTestRoot = [System.IO.Path]::GetFullPath($TestRoot).TrimEnd('\', '/')
  if ($ResolvedTestRoot.StartsWith($SystemTemp + [System.IO.Path]::DirectorySeparatorChar, [System.StringComparison]::OrdinalIgnoreCase) -and
      [System.IO.Path]::GetFileName($ResolvedTestRoot).StartsWith('steel-release-sbom-test-', [System.StringComparison]::Ordinal)) {
    Remove-Item -LiteralPath $ResolvedTestRoot -Recurse -Force -ErrorAction SilentlyContinue
  }
}
